name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@2.11.0
    - run: ./gradlew wrapper && ./gradlew build && ./gradlew test
